import { createContext } from "react"

export const Context = createContext()

export default {
  judul: "Tugas Akhir Aljabar Linier & Matriks",
  logo: "https://fti.unibba.ac.id/wp-content/uploads/2016/07/cropped-Logo-FTI-UNIBBA.png",
  menu: ["Invers Matriks 3x3", "About Us"],
  link: "https://invers-matriks-3x3.vercel.app",
  deskripsi:
    "Kalkulator Invers Matriks 3x3 menggunakan framework Next.js, Tailwind CSS, Math.js, dan MathJax",
  thumbnail: "/images/thumbnail.png",
  keywords: [
    "Tugas akhir aljabar linier dan matriks",
    "Tugas akhir aljabar linier dan matriks next js",
    "Tugas besar aljabar linier dan matriks",
    "Tugas besar aljabar linier dan matriks next js",
    "Tugas akhir aljabar linier dan matriks unibba",
    "Tugas besar aljabar linier dan matriks unibba",
    "Aljabar linier dan matriks",
    "Aljabar linier dan matriks next js",
    "Aljabar linier dan matriks unibba",
    "Aljabar linier dan matriks unibba next js",
    "kalkulator invers matriks 3x3",
    "kalkulator invers matriks 3x3 unibba",
    "kalkulator invers matriks 3x3 next.js",
    "invers matriks 3x3 brainly",
    "invers matriks 3x3 gauss jordan",
    "invers matriks 3x3 contoh soal",
    "invers matriks 3x3 metode adjoin",
    "invers matriks 3x3 obe",
    "invers matriks 3x3 metode sarrus",
    "invers matriks 3x3 kofaktor",
    "invers matriks 3x3 kalkulator",
    "invers matriks 3x3 adjoin",
    "invers matriks 3x3 adalah",
    "invers matriks 3x3 a-1",
    "invers matriks ordo 3x3 adalah",
    "a invers matriks 3x3",
    "invers matriks berordo 3x3",
    "rumus invers matriks 3x3 brainly",
    "cara menentukan invers matriks berordo 3x3",
    "contoh soal invers matriks berordo 3x3",
    "determinan dan invers matriks berordo 3x3",
    "buktikan invers matriks 3x3",
    "contoh soal invers matriks ordo 3x3 beserta jawabannya doc",
    "invers matriks 3x3 calculator",
    "invers matriks 3x3 cara cepat",
    "invers matriks 3x3 c++",
    "contoh invers matriks 3x3",
    "cara invers matriks 3x3 di excel",
    "contoh soal invers matriks 3x3 dan pembahasannya",
    "cara mencari invers matriks 3x3 dengan adjoin",
    "c inverse matrix 3x3",
    "invers matriks 3x3 dengan obe",
    "invers matriks 3x3 dengan adjoin",
    "soal invers matriks 3x3 dan pembahasannya",
    "cara mencari invers matriks 3x3 dengan kofaktor",
    "invers matriks 2x2 dan 3x3",
    "cara mencari invers matriks 3x3 dengan kalkulator",
    "determinan invers matriks 3x3",
    "invers matriks 3x3 excel",
    "hitung invers matriks 3x3",
    "cara hitung invers matriks 3x3",
    "invers matriks 3x3 minor kofaktor",
    "invers matriks ordo 3x3 metode kofaktor",
    "lkpd invers matriks 3x3",
    "invers matriks 3x3 metode gauss jordan",
    "invers matriks 3x3 metode obe",
    "invers matriks 3x3 metode kofaktor",
    "invers matriks 3x3 metode baris elementer",
    "invers matriks 3x3 mathcyber",
    "invers matriks 3x3 online",
    "invers matriks ordo 3x3",
    "invers matriks ordo 3x3 metode gauss jordan",
    "determinan matriks 3x3 obe",
    "invers matriks ordo 3x3 brainly",
    "determinan matriks 3x3 online",
    "invers matriks ordo 3x3 contoh soal",
    "invers matriks 3x3 pdf",
    "invers matriks 3x3 ppt",
    "invers matriks 3x3 persamaan linear",
    "invers matriks ordo 3x3 ppt",
    "invers matriks ordo 3x3 pdf",
    "penyelesaian invers matriks 3x3",
    "program invers matriks 3x3 c++",
    "invers matriks 3x3 ruangguru",
    "rumus invers matriks 3x3",
    "rumus invers matriks ordo 3x3",
    "invers matriks 3x3 soal",
    "invers matriks 3x3 sarrus",
    "spl dengan invers matriks 3x3",
    "contoh soal invers matriks 3x3 brainly",
    "contoh soal invers matriks 3 x 3",
    "tentukan invers matriks 3x3",
    "tentukan invers matriks 3x3 brainly",
    "matriks 3x3 tidak mempunyai invers",
    "tentukan invers matriks ordo 3x3",
  ],
}
